services:
  vllm_llm_serving_api:
    image: vllm/vllm-openai:latest
    container_name: vllm_openai_container
    runtime: nvidia
    ports:
      - "9990:8000"
    volumes:
      - "D:/JYN/EZ/EGITIM/LLM_Model_Registry/HuggingFaceRepo/app/models:/root/.cache/huggingface"
    environment:
      - MODEL_PATH=/root/.cache/huggingface/models--Qwen--Qwen2.5-0.5B-Instruct

    command: >
      --model ${MODEL_PATH}
      --gpu-memory-utilization 0.6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - llm_bridge

networks:
  llm_bridge:
    external: true