# NVIDIA GPU Configuration
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-api-server
    ports:
      - "11434:11434"
    volumes:
      - "D:/JYN/EZ/EGITIM/LLM_Model_Registry/OLLAMA/models:/root/.ollama/models"
    restart: unless-stopped
    networks:
      - ollama-network
    # NVIDIA GPU Configuration (Modern Docker Compose)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Use single GPU
              capabilities: [gpu]
    # Additional GPU environment variables
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_GPU_LAYERS=999
      - OLLAMA_NUM_PARALLEL=4

  api-wrapper:
    build: .
    container_name: ollama-wrapper
    ports:
      - "9999:9999"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ollama-network
    restart: unless-stopped

networks:
  ollama-network:
    driver: bridge